variables:
  IMAGE_NAME: fadhiljr/demo-app
  IMAGE_TAG: juice-shop-1.1
stages:
  - test 
  - build 
  - cache

create_cache:
  image: node:18-bullseye
  stage: cache 
  script:
    - yarn install
  cache:
    key:
      files:
        - yarn.lock 
    paths:
      - node_modules/
      - yarn.lock 
      - .yarn 
    policy: pull-push

gitleaks:
  stage: test 
  image: 
    name: zricethezav/gitleaks
    entrypoint: [""]
  script: 
    - gitleaks detect --verbose --source .
  allow_failure: true

yarn_test:
  image: node:18-bullseye
  stage: test 
  script:
    - yarn install
    - yarn test 

njsscan:
  stage: test 
  image: python 
  before_script:
    - pip3 install --upgrade njsscan
  script: 
    - njsscan --exit-warning .

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_PASS: test123
    DOCKER_USER: fadhiljr
  before_script:
    - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG