apiVersion: v1
kind: Pod
metadata:
  name: privileged
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      privileged: true